# Generated by Django 4.1.5 on 2023-01-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
